spring:
  application:
    name: VideoBackSystem

  datasource:
    #    url: jdbc:mysql://60.204.224.219:3306/
    url: jdbc:mysql://localhost:3306/video_web_project
    username: root
    password: luoxue
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 60.204.224.219
    password: luoxue
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 300


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

video:
  resourcePath: